on:
  registry_package:
    types: [published]

jobs:
  my_example_job:
    runs-on: ubuntu-latest
    name: An example job
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
